<a href="https://colab.research.google.com/github/Dangaretanvi1546/Disease-Symptoms-Prediction-AI/blob/main/Disease_Symptom_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving dataset.csv to dataset (1).csv
Saving symptom_Description.csv to symptom_Description (1).csv
Saving symptom_precaution.csv to symptom_precaution (1).csv
Saving Symptom-severity.csv to Symptom-severity (1).csv

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score, classification_report

import pickle

In [ ]:
dataset = pd.read_csv("dataset.csv")

description = pd.read_csv("symptom_Description.csv")

precaution = pd.read_csv("symptom_precaution.csv")

severity = pd.read_csv("Symptom-severity.csv")

In [ ]:
dataset.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fungal infection,itching,skin_rash,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
description.head()

          Disease                                        Description
0   Drug Reaction  An adverse drug reaction (ADR) is an injury ca...
1         Malaria  An infectious disease caused by protozoan para...
2         Allergy  An allergy is an immune system response to a f...
3  Hypothyroidism  Hypothyroidism, also called underactive thyroi...
4       Psoriasis  Psoriasis is a common skin disorder that forms...

In [ ]:
precaution.head()

,Disease,Precaution_1,Precaution_2,Precaution_3,Precaution_4
0,Drug Reaction,stop irritation,consult nearest hospital,stop taking drug,follow up
1,Malaria,Consult nearest hospital,avoid oily food,avoid non veg food,keep mosquitos out
2,Allergy,apply calamine,cover area with bandage,NaN,use ice to compress itching
3,Hypothyroidism,reduce stress,exercise,eat healthy,get proper sleep
4,Psoriasis,wash hands with warm soapy water,stop bleeding using pressure,consult doctor,salt baths

In [ ]:
severity.head()

                Symptom  weight
0               itching       1
1             skin_rash       3
2  nodal_skin_eruptions       4
3   continuous_sneezing       4
4             shivering       5

In [ ]:
dataset.columns

Index(['Disease', 'Symptom_1', 'Symptom_2', 'Symptom_3', 'Symptom_4',
       'Symptom_5', 'Symptom_6', 'Symptom_7', 'Symptom_8', 'Symptom_9',
       'Symptom_10', 'Symptom_11', 'Symptom_12', 'Symptom_13', 'Symptom_14',
       'Symptom_15', 'Symptom_16', 'Symptom_17'],
      dtype='object')

In [ ]:
symptom_columns = dataset.columns[1:]

dataset["Symptoms"] = dataset[symptom_columns].apply(
    lambda x: ' '.join(x.dropna()),
    axis=1
)

In [ ]:
data = dataset.merge(
    description,
    on="Disease",
    how="left"
)

In [ ]:
data.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17,Symptoms,Description
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,itching skin_rash nodal_skin_eruptions disc...,"In humans, fungal infections occur when an inv..."
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,skin_rash nodal_skin_eruptions dischromic _...,"In humans, fungal infections occur when an inv..."
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,itching nodal_skin_eruptions dischromic _pat...,"In humans, fungal infections occur when an inv..."
3,Fungal infection,itching,skin_rash,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,itching skin_rash dischromic _patches,"In humans, fungal infections occur when an inv..."
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,itching skin_rash nodal_skin_eruptions,"In humans, fungal infections occur when an inv..."

In [ ]:
data.isnull().sum()

Disease           0
Symptom_1         0
Symptom_2         0
Symptom_3         0
Symptom_4       348
Symptom_5      1206
Symptom_6      1986
Symptom_7      2652
Symptom_8      2976
Symptom_9      3228
Symptom_10     3408
Symptom_11     3726
Symptom_12     4176
Symptom_13     4416
Symptom_14     4614
Symptom_15     4680
Symptom_16     4728
Symptom_17     4848
Symptoms          0
Description     360
dtype: int64

In [ ]:
data = data.merge(
    precaution,
    on="Disease",
    how="left"
)

In [ ]:
dataset.shape

(4920, 19)

In [ ]:
data.shape

(4920, 24)

In [ ]:
print(data.shape)

(4920, 24)

In [ ]:
data = data.drop_duplicates()

In [ ]:
data = dataset.merge(
    description,
    on="Disease",
    how="left"
)


data = data.merge(
    precaution,
    on="Disease",
    how="left"
)

In [ ]:
data.shape

(4920, 24)

In [ ]:
data[["Disease","Symptoms"]].head()

            Disease                                           Symptoms
0  Fungal infection  itching  skin_rash  nodal_skin_eruptions  disc...
1  Fungal infection   skin_rash  nodal_skin_eruptions  dischromic _...
2  Fungal infection  itching  nodal_skin_eruptions  dischromic _pat...
3  Fungal infection            itching  skin_rash  dischromic _patches
4  Fungal infection           itching  skin_rash  nodal_skin_eruptions

In [ ]:
X = data["Symptoms"]

y = data["Disease"]

tfidf = TfidfVectorizer()

X = tfidf.fit_transform(X)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
model = MultinomialNB()

In [ ]:
model.fit(X_train,y_train)

MultinomialNB()

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
accuracy = accuracy_score(
    y_test,
    y_pred
)

print("Accuracy:",accuracy)

Accuracy: 1.0

In [ ]:
print(classification_report(y_test,y_pred))

                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        18
                                   AIDS       1.00      1.00      1.00        30
                                   Acne       1.00      1.00      1.00        24
                    Alcoholic hepatitis       1.00      1.00      1.00        25
                                Allergy       1.00      1.00      1.00        24
                              Arthritis       1.00      1.00      1.00        23
                       Bronchial Asthma       1.00      1.00      1.00        33
                   Cervical spondylosis       1.00      1.00      1.00        23
                            Chicken pox       1.00      1.00      1.00        21
                    Chronic cholestasis       1.00      1.00      1.00        15
                            Common Cold       1.00      1.00      1.00        23
                                 Dengue       1.00      1.00      1.00        26
                              Diabetes        1.00      1.00      1.00        21
           Dimorphic hemmorhoids(piles)       1.00      1.00      1.00        29
                          Drug Reaction       1.00      1.00      1.00        24
                       Fungal infection       1.00      1.00      1.00        19
                                   GERD       1.00      1.00      1.00        28
                        Gastroenteritis       1.00      1.00      1.00        25
                           Heart attack       1.00      1.00      1.00        23
                            Hepatitis B       1.00      1.00      1.00        27
                            Hepatitis C       1.00      1.00      1.00        26
                            Hepatitis D       1.00      1.00      1.00        23
                            Hepatitis E       1.00      1.00      1.00        29
                          Hypertension        1.00      1.00      1.00        25
                        Hyperthyroidism       1.00      1.00      1.00        24
                           Hypoglycemia       1.00      1.00      1.00        26
                         Hypothyroidism       1.00      1.00      1.00        21
                               Impetigo       1.00      1.00      1.00        24
                               Jaundice       1.00      1.00      1.00        19
                                Malaria       1.00      1.00      1.00        22
                               Migraine       1.00      1.00      1.00        25
                        Osteoarthristis       1.00      1.00      1.00        22
           Paralysis (brain hemorrhage)       1.00      1.00      1.00        24
                    Peptic ulcer diseae       1.00      1.00      1.00        17
                              Pneumonia       1.00      1.00      1.00        28
                              Psoriasis       1.00      1.00      1.00        22
                           Tuberculosis       1.00      1.00      1.00        25
                                Typhoid       1.00      1.00      1.00        19
                Urinary tract infection       1.00      1.00      1.00        26
                         Varicose veins       1.00      1.00      1.00        22
                            hepatitis A       1.00      1.00      1.00        34

                               accuracy                           1.00       984
                              macro avg       1.00      1.00      1.00       984
                           weighted avg       1.00      1.00      1.00       984

In [ ]:
new_symptoms = ["itching skin rash"]

new_data = tfidf.transform(new_symptoms)

prediction = model.predict(new_data)

print("Disease:",prediction[0])

Disease: Chronic cholestasis

In [ ]:
disease = prediction[0]


result = data[data["Disease"] == disease]


print("Disease:")
print(disease)


print("\nDescription:")
print(result["Description"].values[0])


print("\nPrecautions:")

print(result["Precaution_1"].values[0])
print(result["Precaution_2"].values[0])
print(result["Precaution_3"].values[0])
print(result["Precaution_4"].values[0])

Disease:
Chronic cholestasis

Description:
Chronic cholestatic diseases, whether occurring in infancy, childhood or adulthood, are characterized by defective bile acid transport from the liver to the intestine, which is caused by primary damage to the biliary epithelium in most cases

Precautions:
cold baths
anti itch medicine
consult doctor
eat healthy

In [ ]:
pickle.dump(
    model,
    open("disease_model.pkl","wb")
)


pickle.dump(
    tfidf,
    open("tfidf.pkl","wb")
)